import type { Exercise } from '../types';

const now = new Date().toISOString();

export const seedExercises: Exercise[] = [
  {
    id: crypto.randomUUID(),
    name: 'Klimmzug',
    muscleGroups: ['Rücken', 'Bizeps'],
    deviceNumber: 17,
    order: 1,
    optional: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 42,
    weightUnit: 'kg',
    settings: [],
    notes: 'Assistiert — 42 kg Gegengewicht',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    name: 'Beinpresse',
    muscleGroups: ['Beine', 'Gesäß'],
    deviceNumber: 1,
    order: 2,
    optional: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 90,
    weightUnit: 'kg',
    settings: [{ label: 'Sitz', value: '3' }],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    name: 'Rudern am Kabel',
    muscleGroups: ['Rücken'],
    deviceNumber: 16,
    order: 3,
    optional: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 35,
    weightUnit: 'kg',
    settings: [],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    name: 'Butterfly',
    muscleGroups: ['Brust'],
    deviceNumber: 11,
    order: 4,
    optional: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 12.5,
    weightUnit: 'kg',
    settings: [
      { label: 'Position', value: '2' },
      { label: 'Sitz', value: '3' },
      { label: 'Stift', value: '2,5 kg' },
    ],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    name: 'Armdrücken am Kabel',
    muscleGroups: ['Trizeps'],
    deviceNumber: 18,
    order: 5,
    optional: true,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 15,
    weightUnit: 'kg',
    settings: [
      { label: 'Höhe', value: '36' },
      { label: 'Griff', value: '↓' },
    ],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    name: 'Armbeugen am Kabel',
    muscleGroups: ['Bizeps'],
    deviceNumber: 18,
    order: 6,
    optional: true,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 12.5,
    weightUnit: 'kg',
    settings: [
      { label: 'Höhe', value: '1' },
      { label: 'Griff', value: '↑' },
    ],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    name: 'Hyperextension',
    muscleGroups: ['Unterer Rücken'],
    deviceNumber: 14,
    order: 7,
    optional: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: null,
    weightUnit: 'bw',
    settings: [{ label: 'Position', value: '3' }],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: crypto.randomUUID(),
    name: 'Rumpfrotation',
    muscleGroups: ['Seitl. Bauch'],
    deviceNumber: 2,
    order: 8,
    optional: false,
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 10,
    weightUnit: 'kg',
    settings: [{ label: 'Position', value: '3' }],
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
];
